/**
 * Byte store for private documents. Implementations are swapped at the
 * composition root: an in-memory store for tests, a local-filesystem store for
 * development, and (later) an S3-compatible store for deployment. Keys are
 * opaque ids generated by the caller — never a user-supplied name or path.
 */
export interface FileStorage {
  /** Write bytes under `key`. Must reject if `key` already exists. */
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  /** Read bytes, or `null` if the key is unknown. */
  get(key: string): Promise<Buffer | null>;
  /** Remove `key`. Idempotent — a missing key is not an error. */
  delete(key: string): Promise<void>;
}

/** Opaque storage keys we accept: our own generated ids only. */
export const STORAGE_KEY_PATTERN = /^[a-zA-Z0-9._-]{1,200}$/;

export function assertStorageKey(key: string): void {
  if (!STORAGE_KEY_PATTERN.test(key) || key.includes('..')) {
    throw new Error('Invalid storage key');
  }
}

export function createInMemoryFileStorage(): FileStorage {
  const store = new Map<string, Buffer>();
  return {
    async put(key, bytes) {
      assertStorageKey(key);
      if (store.has(key)) throw new Error(`Storage key already exists: ${key}`);
      store.set(key, Buffer.from(bytes));
    },
    async get(key) {
      assertStorageKey(key);
      const value = store.get(key);
      return value ? Buffer.from(value) : null;
    },
    async delete(key) {
      assertStorageKey(key);
      store.delete(key);
    },
  };
}

/**
 * Fails closed. No object-storage provider is approved yet (deferred to
 * infrastructure approval — see docs/DOCUMENTS.md), so a deployed
 * environment that reaches this adapter must not silently accept an upload
 * it cannot durably store.
 */
export function createUnconfiguredFileStorage(): FileStorage {
  const unconfigured = async () => {
    throw new Error(
      'File storage is not configured for this environment. Wire an approved object-storage ' +
        'adapter before documents can be uploaded (see docs/DOCUMENTS.md).',
    );
  };
  return { put: unconfigured, get: unconfigured, delete: unconfigured };
}
